# Generated by Django 3.1.7 on 2021-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='kind',
            field=models.CharField(choices=[('VE', 'Vegetariana'), ('VG', 'Vegana'), ('CA', 'Carne')], default='CA', max_length=100),
        ),
    ]
